import fs from 'fs';
import path from 'path';
import archiver from 'archiver';
import { ZALO_CONFIG } from '../config.js';

export interface FileValidationResult {
  valid: boolean;
  totalSizeMB: number;
  oversizedFiles: { file: string; sizeMB: number }[];
  invalidExtensionFiles: string[];
  missingRequiredFiles: string[];
  warnings: string[];
}

export function getAllFiles(dir: string, baseDir: string = dir): string[] {
  let results: string[] = [];
  if (!fs.existsSync(dir)) return results;

  const list = fs.readdirSync(dir, { withFileTypes: true });
  for (const item of list) {
    const fullPath = path.join(dir, item.name);
    if (item.isDirectory()) {
      results = results.concat(getAllFiles(fullPath, baseDir));
    } else {
      results.push(path.relative(baseDir, fullPath).replace(/\\/g, '/'));
    }
  }
  return results;
}

export function validateOutputDir(outputDir: string): FileValidationResult {
  const result: FileValidationResult = {
    valid: true,
    totalSizeMB: 0,
    oversizedFiles: [],
    invalidExtensionFiles: [],
    missingRequiredFiles: [],
    warnings: [],
  };

  if (!fs.existsSync(outputDir)) {
    result.valid = false;
    result.warnings.push(`Output directory not found: ${outputDir}`);
    return result;
  }

  const files = getAllFiles(outputDir);

  // Check required app-config.json
  if (!files.includes('app-config.json')) {
    result.missingRequiredFiles.push('app-config.json');
    result.valid = false;
  }

  let totalBytes = 0;
  for (const relPath of files) {
    const fullPath = path.join(outputDir, relPath);
    const stat = fs.statSync(fullPath);
    totalBytes += stat.size;

    const sizeMB = stat.size / (1024 * 1024);
    if (sizeMB > ZALO_CONFIG.LIMITS.maxFileSizeMB) {
      result.oversizedFiles.push({ file: relPath, sizeMB: parseFloat(sizeMB.toFixed(2)) });
      result.valid = false;
    }

    const ext = path.extname(relPath).toLowerCase();
    if (!ZALO_CONFIG.LIMITS.allowedExtensions.includes(ext)) {
      if (relPath === 'index.html') {
        result.warnings.push(
          'index.html will NOT be served directly by Zalo. Ensure your JS/CSS entry points are registered in app-config.json'
        );
      } else {
        result.invalidExtensionFiles.push(relPath);
        result.valid = false;
      }
    }
  }

  result.totalSizeMB = parseFloat((totalBytes / (1024 * 1024)).toFixed(2));
  if (result.totalSizeMB > ZALO_CONFIG.LIMITS.maxZipSizeMB) {
    result.valid = false;
    result.warnings.push(
      `Total bundle size (${result.totalSizeMB} MB) exceeds maximum allowed limit (${ZALO_CONFIG.LIMITS.maxZipSizeMB} MB)`
    );
  }

  return result;
}

export async function zipDirectory(dir: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const archive = archiver('zip', { zlib: { level: 9 } });
    const buffers: Buffer[] = [];

    archive.on('data', (data) => buffers.push(data));
    archive.on('end', () => resolve(Buffer.concat(buffers)));
    archive.on('error', (err) => reject(err));

    archive.directory(dir, false);
    archive.finalize();
  });
}

export function syncAppConfigAssets(projectDir: string, outputDirName: string = 'www') {
  const rootConfigPath = path.join(projectDir, 'app-config.json');
  const rootAppJsonPath = path.join(projectDir, 'app.json');
  const outConfigPath = path.join(projectDir, outputDirName, 'app-config.json');
  const assetsDir = path.join(projectDir, outputDirName, 'assets');

  if (!fs.existsSync(rootConfigPath)) {
    throw new Error(`app-config.json not found in project root: ${projectDir}`);
  }

  const config = JSON.parse(fs.readFileSync(rootConfigPath, 'utf8'));

  // If output directory has app-config.json with assets already generated by Vite
  if (fs.existsSync(outConfigPath)) {
    try {
      const outConfig = JSON.parse(fs.readFileSync(outConfigPath, 'utf8'));
      if (outConfig.listCSS) config.listCSS = outConfig.listCSS;
      if (outConfig.listSyncJS) config.listSyncJS = outConfig.listSyncJS;
      if (outConfig.listAsyncJS) config.listAsyncJS = outConfig.listAsyncJS;
    } catch {
      // fallback to scanning assets dir
    }
  }

  // Fallback scan if listCSS / listAsyncJS are empty
  if ((!config.listCSS || config.listCSS.length === 0) && fs.existsSync(assetsDir)) {
    const assetFiles = fs.readdirSync(assetsDir);
    config.listCSS = assetFiles
      .filter((f) => f.endsWith('.css'))
      .map((f) => `assets/${f}`);
    config.listAsyncJS = assetFiles
      .filter((f) => f.endsWith('.js'))
      .map((f) => `assets/${f}`);
    if (!config.listSyncJS) config.listSyncJS = [];
  }

  // Write back to both root config, app.json and output config
  fs.writeFileSync(rootConfigPath, JSON.stringify(config, null, 2), 'utf8');
  if (fs.existsSync(rootAppJsonPath) || !fs.existsSync(rootAppJsonPath)) {
    fs.writeFileSync(rootAppJsonPath, JSON.stringify(config, null, 2), 'utf8');
  }
  if (fs.existsSync(path.join(projectDir, outputDirName))) {
    fs.writeFileSync(outConfigPath, JSON.stringify(config, null, 2), 'utf8');
  }

  return config;
}
